### ISSUE TITLE
A few days ago, stopped from showing bus lines

### ISSUE THREAD

**Issue by MosheRabeynu** [silentbil/silent-bus#10]
A few days ago, stopped from showing bus lines in Android app. On PC works fine.
Screenshot attached for example
![Screenshot_20240703_161012_Home Assistant](https://github.com/silentbil/silent-bus/assets/163451257/6d352cac-9fd3-4fb3-83a2-8432b68e3c14)

**Comment by Gugulator** [comment]
Same problem.
Message in system log: Failed to execute 'define' on 'CustomElementRegistry': the name "silent-bus" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/silent-bus/silent-bus.js:262:356

system info:
Core - 2024.7.0
Supervisor - 2024.06.2
Operating System - 12.4
Frontend - 20240703.0

**Comment by silentbil** [comment]
Hi
seem like a cors issue
will try to fix soon

**Comment by silentbil** [comment]
Fixed, plz update the card to a newer version :)

if u like my hard work consider buying me a coffee :) 
<a href="https://www.buymeacoffee.com/silentbil" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: 41px !important;width: 174px !important;box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;-webkit-box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;" ></a>

**Comment by Gugulator** [comment]
Problem comes back

Uncaught error from Brave 126.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "silent-bus" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/silent-bus/silent-bus.js:241:356

**Comment by silentbil** [comment]
i get blocked from a 3d party bus data center
trying to solve it

**Comment by Gugulator** [comment]
After updating to version 1.18 still not working.
Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: July 12, 2024 at 01:07:16 (15 occurrences)
Last logged: 23:56:29

Uncaught error from Chrome WebView 126.0.6478.134 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "silent-bus" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/silent-bus/silent-bus.js:241:356
Uncaught error from Chrome WebView 126.0.6478.134 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "silent-bus" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/silent-bus/silent-bus.js:243:356

**Comment by MDV85** [comment]
> i get blocked from a 3d party bus data center trying to solve it

Any news?

**Comment by silentbil** [comment]
> > i get blocked from a 3d party bus data center trying to solve it
> 
> Any news?

Yes. im working on a solution, a more complex one
hopefuly will release it in this week

**Comment by silentbil** [comment]
Ok , released a new version. plz try upgrade and let me know

**Comment by MosheRabeynu** [comment]
Well, Thanks!!

It works and that's great, but two small things:
1. Seems like it doesn't retrieve bus station name.
2. Takes a lot of time to load the card, or refresh it. But that's not
really an issue...

**Comment by Gugulator** [comment]
First of all thank you for great work and fixing the bug.
But i can confirm that it works much slower than before. Probably because of retrieving not only closest time of the bus, but also a few next ones.

**Comment by silentbil** [comment]
yes, so few things to know
1. i now own a server which is on a free tier, therfor it go to sleep every 15min, and on wake up can lead to slow request like ~20 sec . to improve this i would need to buy an upgrade plan that cost more
2. im currently showing only the "live" data, so if the bus is not in 1 hour to come,  it might not show it.
3. i will improve it to get also "not live" data, but schedules so it will be much more rich data

**Comment by MDV85** [comment]
> yes, so few things to know
> 
> 1. i now own a server which is on a free tier, therfor it go to sleep every 15min, and on wake up can lead to slow request like ~20 sec . to improve this i would need to buy an upgrade plan that cost more
> 2. im currently showing only the "live" data, so if the bus is not in 1 hour to come,  it might not show it.
> 3. i will improve it to get also "not live" data, but schedules so it will be much more rich data

It doesn't work for me, I don't know why
![ScreenShot01 Aug  06 10 19](https://github.com/user-attachments/assets/e34d6aef-c28a-4b91-bc77-8b3ed6c8c525)

**Comment by Gugulator** [comment]
Home Assistant
Core 2024.8.0
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240806.1

Silent bus card 1.19
Logs message: 
Logger: frontend.js.modern.202408061
Source: components/system_log/__init__.py:333
First occurred: 23:36:25 (3 occurrences)
Last logged: 23:42:11

Uncaught error from Brave 126.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "silent-bus" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/silent-bus/silent-bus.js:234:356

in addition, i have 2 cards: one with bus station near my home and second near my workplace.
with current version it shows some non-actual names for bus stations - same names for both of them. But the numbers of bus lines are correct. And again, displaying numbers of bus lines takes too much time in day hours
![image](https://github.com/user-attachments/assets/8b26496f-9da1-48b0-97f5-e2a3b0b7e9ba)

**Comment by silentbil** [comment]
Hi @Gugulator 
i fixed the station name, was a bug, plz let me know if it fixed.
will do my best to improve the loading time

**Comment by silentbil** [comment]
I also fixed the time performance :)

**Comment by Gugulator** [comment]
Hi @silentbil 
Update still not available

**Comment by silentbil** [comment]
@Gugulator isnt it good to display more times?

**Comment by Gugulator** [comment]
> @Gugulator isnt it good to display more times?

I think it's ok to cut it up to 2 versions, the closest time and next one. And display only numbers of minutes or seconds, without "min" or "sec". It will not change the form of each line, making it too high. Minimum symbols will prevent multiple lines of text inside each row

**Comment by MDV85** [comment]
> @silentbil Hi!
![ScreenShot01 Aug  09 18 33](https://github.com/user-attachments/assets/e78624a2-5fc1-4641-bd55-817b0a8a3d24)


Why?

**Comment by silentbil** [comment]
@MDV85 u need to upgrade, u are probably in old version

**Comment by silentbil** [comment]
closing this as it was resolved

**Comment by MosheRabeynu** [comment]
Hi @siletntbil,

Previously it showed times of light train.
Now doesn't.

I have used it as bus station:


type: custom:silent-bus
station: 20703
busLines:
  - R3
  - R2

Would you please check it?
